name:                true42
version:             0.1.0.0
github:              "gdmcbain/true42"
license:             BSD3
author:              "G. D. McBain"
maintainer:          "gmcbain@memjet.com"
copyright:           "(c) 2018 G. D. McBain"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Generics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gdmcbain/true42#readme>

dependencies:
- base >= 4.7 && < 5
- generics-sop >= 0.3.2

library:
  source-dirs: src

executables:
  true42-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - true42

tests:
  true42-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - true42
